### ISSUE TITLE
Cannot play audio

### ISSUE THREAD

**Issue by thenoobtester** [MustafaHi/Recast#1]
Hi,

this looks like a great app. Unfortunately when I run it on Debian Stretch 9 I get the following error when I tried to play a podcast:

`Error: Element (Element(<video#tape>)) has no method - videoUnload
	at play
	at `

I know the audio exists because when i click on the "link" button and I got to the link on a browser it works.

When I try to download the podcast i get:

`Error: Wrong type - #NaN, expected instance of float,integer
	at download.progress
`

When I run ldd Recast, It doesn't report any missing library so i don't understand where the problem comes from.

It would be so great if it worked.

Thank you for your help.

**Comment by MustafaHi** [comment]
Thank you for your report, 
unfortunately it appears the framework the software relies on has limited support for Linux,
I applied few work arounds such as sending the file to be played by system when clicking 'play',
as of the download it should work now.

I have updated the Linux release.

**Comment by thenoobtester** [comment]
Thank you for these modifications :)

**Comment by thenoobtester** [comment]
Just a quick question could you please push those modifications to github cause I would like to make a quick modification to launch a script instead of the system default for links which is the browser. Thank you.

**Comment by MustafaHi** [comment]
A better solution is in the work for Linux systems providing a closer experience to what is originally intended.
That and other changes to enhancements will be available in v1.1

**Comment by MustafaHi** [comment]
A better playback solution is in the work for Linux systems providing a closer experience to what is originally intended.
That and other enhancements will be available in v1.1
